class Country < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[Country, ActiveRecord_Relation, Integer]

  module GeneratedAttributeMethods
    def id: () -> Integer

    def id=: (Integer) -> Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ Integer?, Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> Array[Integer?]?

    def id_previously_was: () -> Integer?

    def id_before_last_save: () -> Integer?

    def id_change_to_be_saved: () -> Array[Integer?]?

    def id_in_database: () -> Integer?

    def saved_change_to_id: () -> Array[Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def name: () -> String?

    def name=: (String?) -> String?

    def name?: () -> bool

    def name_changed?: () -> bool

    def name_change: () -> [ String?, String? ]

    def name_will_change!: () -> void

    def name_was: () -> String?

    def name_previously_changed?: () -> bool

    def name_previous_change: () -> Array[String?]?

    def name_previously_was: () -> String?

    def name_before_last_save: () -> String?

    def name_change_to_be_saved: () -> Array[String?]?

    def name_in_database: () -> String?

    def saved_change_to_name: () -> Array[String?]?

    def saved_change_to_name?: () -> bool

    def will_save_change_to_name?: () -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def code: () -> String?

    def code=: (String?) -> String?

    def code?: () -> bool

    def code_changed?: () -> bool

    def code_change: () -> [ String?, String? ]

    def code_will_change!: () -> void

    def code_was: () -> String?

    def code_previously_changed?: () -> bool

    def code_previous_change: () -> Array[String?]?

    def code_previously_was: () -> String?

    def code_before_last_save: () -> String?

    def code_change_to_be_saved: () -> Array[String?]?

    def code_in_database: () -> String?

    def saved_change_to_code: () -> Array[String?]?

    def saved_change_to_code?: () -> bool

    def will_save_change_to_code?: () -> bool

    def restore_code!: () -> void

    def clear_code_change: () -> void
  end
  include GeneratedAttributeMethods
  def places: () -> Place::ActiveRecord_Associations_CollectionProxy
  def places=: (Place::ActiveRecord_Associations_CollectionProxy | Array[Place]) -> (Place::ActiveRecord_Associations_CollectionProxy | Array[Place])
  def place_ids: () -> Array[Integer]
  def place_ids=: (Array[Integer]) -> Array[Integer]
  def profiles: () -> Profile::ActiveRecord_Associations_CollectionProxy
  def profiles=: (Profile::ActiveRecord_Associations_CollectionProxy | Array[Profile]) -> (Profile::ActiveRecord_Associations_CollectionProxy | Array[Profile])
  def profile_ids: () -> Array[Integer]
  def profile_ids=: (Array[Integer]) -> Array[Integer]

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[Country, Integer]
    include Enumerable[Country]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[Country, Integer]
  end
end
