class Sponsor < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[Sponsor, ActiveRecord_Relation, Integer]

  module GeneratedAttributeMethods
    def id: () -> Integer

    def id=: (Integer) -> Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ Integer?, Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> Array[Integer?]?

    def id_previously_was: () -> Integer?

    def id_before_last_save: () -> Integer?

    def id_change_to_be_saved: () -> Array[Integer?]?

    def id_in_database: () -> Integer?

    def saved_change_to_id: () -> Array[Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def name: () -> String?

    def name=: (String?) -> String?

    def name?: () -> bool

    def name_changed?: () -> bool

    def name_change: () -> [ String?, String? ]

    def name_will_change!: () -> void

    def name_was: () -> String?

    def name_previously_changed?: () -> bool

    def name_previous_change: () -> Array[String?]?

    def name_previously_was: () -> String?

    def name_before_last_save: () -> String?

    def name_change_to_be_saved: () -> Array[String?]?

    def name_in_database: () -> String?

    def saved_change_to_name: () -> Array[String?]?

    def saved_change_to_name?: () -> bool

    def will_save_change_to_name?: () -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def website: () -> String?

    def website=: (String?) -> String?

    def website?: () -> bool

    def website_changed?: () -> bool

    def website_change: () -> [ String?, String? ]

    def website_will_change!: () -> void

    def website_was: () -> String?

    def website_previously_changed?: () -> bool

    def website_previous_change: () -> Array[String?]?

    def website_previously_was: () -> String?

    def website_before_last_save: () -> String?

    def website_change_to_be_saved: () -> Array[String?]?

    def website_in_database: () -> String?

    def saved_change_to_website: () -> Array[String?]?

    def saved_change_to_website?: () -> bool

    def will_save_change_to_website?: () -> bool

    def restore_website!: () -> void

    def clear_website_change: () -> void

    def sponsorable_id: () -> Integer?

    def sponsorable_id=: (Integer?) -> Integer?

    def sponsorable_id?: () -> bool

    def sponsorable_id_changed?: () -> bool

    def sponsorable_id_change: () -> [ Integer?, Integer? ]

    def sponsorable_id_will_change!: () -> void

    def sponsorable_id_was: () -> Integer?

    def sponsorable_id_previously_changed?: () -> bool

    def sponsorable_id_previous_change: () -> Array[Integer?]?

    def sponsorable_id_previously_was: () -> Integer?

    def sponsorable_id_before_last_save: () -> Integer?

    def sponsorable_id_change_to_be_saved: () -> Array[Integer?]?

    def sponsorable_id_in_database: () -> Integer?

    def saved_change_to_sponsorable_id: () -> Array[Integer?]?

    def saved_change_to_sponsorable_id?: () -> bool

    def will_save_change_to_sponsorable_id?: () -> bool

    def restore_sponsorable_id!: () -> void

    def clear_sponsorable_id_change: () -> void

    def created_at: () -> ActiveSupport::TimeWithZone

    def created_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: () -> bool

    def created_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: () -> bool

    def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> Array[ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def updated_at: () -> ActiveSupport::TimeWithZone

    def updated_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: () -> bool

    def updated_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: () -> bool

    def updated_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> Array[ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def sponsorable_type: () -> String?

    def sponsorable_type=: (String?) -> String?

    def sponsorable_type?: () -> bool

    def sponsorable_type_changed?: () -> bool

    def sponsorable_type_change: () -> [ String?, String? ]

    def sponsorable_type_will_change!: () -> void

    def sponsorable_type_was: () -> String?

    def sponsorable_type_previously_changed?: () -> bool

    def sponsorable_type_previous_change: () -> Array[String?]?

    def sponsorable_type_previously_was: () -> String?

    def sponsorable_type_before_last_save: () -> String?

    def sponsorable_type_change_to_be_saved: () -> Array[String?]?

    def sponsorable_type_in_database: () -> String?

    def saved_change_to_sponsorable_type: () -> Array[String?]?

    def saved_change_to_sponsorable_type?: () -> bool

    def will_save_change_to_sponsorable_type?: () -> bool

    def restore_sponsorable_type!: () -> void

    def clear_sponsorable_type_change: () -> void

    def logo_data: () -> untyped?

    def logo_data=: (untyped?) -> untyped?

    def logo_data?: () -> bool

    def logo_data_changed?: () -> bool

    def logo_data_change: () -> [ untyped?, untyped? ]

    def logo_data_will_change!: () -> void

    def logo_data_was: () -> untyped?

    def logo_data_previously_changed?: () -> bool

    def logo_data_previous_change: () -> Array[untyped?]?

    def logo_data_previously_was: () -> untyped?

    def logo_data_before_last_save: () -> untyped?

    def logo_data_change_to_be_saved: () -> Array[untyped?]?

    def logo_data_in_database: () -> untyped?

    def saved_change_to_logo_data: () -> Array[untyped?]?

    def saved_change_to_logo_data?: () -> bool

    def will_save_change_to_logo_data?: () -> bool

    def restore_logo_data!: () -> void

    def clear_logo_data_change: () -> void
  end
  include GeneratedAttributeMethods

  def sponsorable: () -> untyped
  def sponsorable=: (untyped?) -> untyped?
  def reload_sponsorable: () -> untyped?

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[Sponsor, Integer]
    include Enumerable[Sponsor]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[Sponsor, Integer]
  end
end
