module Api
  module V1
    module Suits
      class PopularitiesController < ApplicationController
        def show: () -> untyped

        private

        def popularity_params: () -> untyped
      end
    end
  end
end
