FROM rails:4.2

MAINTAINER Aleksandr Kunin <skyksandr@gmail.com>

RUN echo "gem: --no-rdoc --no-ri" >> ~/.gemrc

WORKDIR /tmp
COPY ./Gemfile Gemfile
COPY ./Gemfile.lock Gemfile.lock
RUN bundle install --jobs 20 --retry 5

WORKDIR /opt/app

EXPOSE 3000

CMD ["rails", "server", "--binding", "0.0.0.0"]
