module EventScoped
  type scoreboard = Events::Scoreboards::SpeedDistanceTime | Events::Scoreboards::HungaryBoogie

  extend ActiveSupport::Concern

  @scoreboard: scoreboard
  @event: Event
  @scoreboard_params: Events::Scoreboards::Params

  def display_event_params: () -> ::ActionController::Parameters
  def respond_with_scoreboard: () -> void
  def respond_with_errors: (ActiveModel::Errors errors) -> void
  def create_scoreboard: (event_id: int) -> scoreboard
  def load_event: (event_id: int) -> void
  def scoreboard_params: (Event event) -> Events::Scoreboards::Params
  def authorize_event: () -> void
end
