module Api
  module V1
    module Tracks
      class FilesController < ApplicationController
        def create: () -> untyped

        private

        def track_file_params: () -> untyped
      end
    end
  end
end
