module Api
  module V1
    class SuitsController < Api::ApplicationController
      def index: () -> untyped

      def show: () -> untyped

      private

      def apply_filters: (untyped relation) -> untyped
    end
  end
end
