export { default as useCreateCompetitorMutation } from './useCreateCompetitorMutation'
export { default as useUpdateCompetitorMutation } from './useUpdateCompetitorMutation'
export { default as useDeleteCompetitorMutation } from './useDeleteCompetitorMutation'
export type { CompetitorVariables, Competitor } from './common'
export { competitorSchema } from './common'
