module Assets
  module SpeedSkydivingCompetitions
    class ScoreboardsController < ApplicationController
      def show: () -> untyped

      private

      def filename: () -> ::String

      def set_event: () -> untyped
    end
  end
end
