module Events
  class ScoreboardsController < ApplicationController
    include EventScoped

    def show: () -> untyped

    private

    def set_event: () -> untyped

    def set_scoreboard: () -> untyped
  end
end
