class ProfilesController < ApplicationController
  def index: () -> untyped

  def show: () -> untyped

  def edit: () -> untyped

  def update: () -> untyped

  def destroy: () -> untyped

  private

  def set_profile: () -> untyped

  def profile_params: () -> untyped
end
