development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= "redis://#{Rails.application.credentials.dig(:redis, :host) || ENV['REDIS_HOST']}:#{Rails.application.credentials.dig(:redis, :port) || ENV['REDIS_PORT']}/#{ENV['REDIS_CABLE_DB']}" %>
