production: &default
  adapter: postgresql
  database: <%= Rails.application.credentials.dig(:database, :name) || ENV['DB_NAME'] %>
  host:     <%= Rails.application.credentials.dig(:database, :host) || ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] || 5432 %>
  username: <%= Rails.application.credentials.dig(:database, :username) || ENV['DB_USERNAME'] %>
  password: <%= Rails.application.credentials.dig(:database, :password) || ENV['DB_PASSWORD'] %>
  encoding: utf8
  timeout: 2000

development:
  <<: *default
  pool: <%= ENV['DB_POOL'] || 5 %>

test: &test
  <<: *default
  database: <%= ENV['DB_TEST_NAME'] %>
