service: skyderby

image: skyderby/app

servers:
  web:
    - 88.99.213.244
  workers:
    cmd: bundle exec sidekiq
    hosts:
      - 88.99.213.244

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  hosts:
    - skyderby.io
    - www.skyderby.io

env:
  clear:
    WEB_CONCURRENCY: 4
    RAILS_MAX_THREADS: 5
    PORT: 80
    ACTIONCABLE_ALLOWED_ORIGINS: https://skyderby.io
    RAILS_SERVE_STATIC_FILES: 1
    REDIS_DB: 12
    REDIS_CABLE_DB: 11
  secret:
    - RAILS_MASTER_KEY

registry: &registry
  server: ghcr.io
  username: <%= ENV.fetch('KAMAL_REGISTRY_USERNAME', 'skyksandr') %>
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  cache:
    type: registry
    options: mode=max

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  runner: app exec --interactive --reuse "bin/rails runner"
  logs: app logs -f

volumes:
 - app_storage:/app/public/system

#asset_path: /app/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2
