test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>

local:
  service: Disk
  root: <%= Rails.root.join('storage') %>

r2:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:r2, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:r2, :secret_access_key) %>
  bucket: <%= Rails.application.credentials.dig(:r2, :bucket) %>
  endpoint: <%= Rails.application.credentials.dig(:r2, :endpoint) %>
  region: auto
  force_path_style: true
  request_checksum_calculation: when_required
  response_checksum_validation: when_required
