class TournamentPolicy < ApplicationPolicy
  def index?: () -> true

  def show?: () -> true

  def update?: () -> untyped

  def organizer?: () -> (false | untyped)

  def responsible?: () -> (false | untyped)

  class Scope < Scope
    def resolve: () -> untyped
  end
end
