class Api::V1::PerformanceCompetitions::RoundsController < ApplicationController
  def index: () -> untyped

  def create: () -> untyped

  def destroy: () -> untyped

  private

  def set_event: () -> untyped

  def round_params: () -> untyped
end
