module Tracks
  module ValuePresenters
    class Distance
      def initialize: (?::String unit_system) -> void

      def call: (untyped value) -> untyped

      private

      attr_reader unit_system: untyped

      def convert: (untyped value) -> untyped
    end
  end
end
