module Tournaments
  module Qualifications
    class CompetitorsCollection
      include Enumerable

      def initialize: (untyped tournament_competitors, untyped scoreboard) -> void

      private

      attr_reader tournament_competitors: untyped

      attr_reader scoreboard: untyped

      def competitors: () -> untyped

      def map_competitors: (untyped collection) -> untyped

      def sort_competitors: (untyped collection) -> untyped
    end
  end
end
