require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe VirtualCompGroupsController, type: :controller do
  before :each do
    @user = FactoryGirl.create(:user)
    @user.stub(:has_role?).and_return(true)
    @abilities = Ability.new(@user)
    Ability.stub(:new).and_return(@abilities)
  end
  # This should return the minimal set of attributes required to create a valid
  # VirtualCompGroup. As you add validations to VirtualCompGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { name: 'Some good competition group' }
  end

  let(:invalid_attributes) do
    { name: nil }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VirtualCompGroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all virtual_comp_groups as @virtual_comp_groups' do
      virtual_comp_group = VirtualCompGroup.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:virtual_comp_groups)).to eq([virtual_comp_group])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested virtual_comp_group as @virtual_comp_group' do
      virtual_comp_group = VirtualCompGroup.create! valid_attributes
      get :show, { id: virtual_comp_group.to_param }, valid_session
      expect(assigns(:virtual_comp_group)).to eq(virtual_comp_group)
    end
  end

  describe 'GET #new' do
    it 'assigns a new virtual_comp_group as @virtual_comp_group' do
      get :new, {}, valid_session
      expect(assigns(:virtual_comp_group)).to be_a_new(VirtualCompGroup)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested virtual_comp_group as @virtual_comp_group' do
      virtual_comp_group = VirtualCompGroup.create! valid_attributes
      get :edit, { id: virtual_comp_group.to_param }, valid_session
      expect(assigns(:virtual_comp_group)).to eq(virtual_comp_group)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new VirtualCompGroup' do
        expect do
          post :create, { virtual_comp_group: valid_attributes }, valid_session
        end.to change(VirtualCompGroup, :count).by(1)
      end

      it 'assigns a newly created virtual_comp_group as @virtual_comp_group' do
        post :create, { virtual_comp_group: valid_attributes }, valid_session
        expect(assigns(:virtual_comp_group)).to be_a(VirtualCompGroup)
        expect(assigns(:virtual_comp_group)).to be_persisted
      end

      it 'redirects to the created virtual_comp_group' do
        post :create, { virtual_comp_group: valid_attributes }, valid_session
        expect(response).to redirect_to(VirtualCompGroup.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved virtual_comp_group as @virtual_comp_group' do
        post :create, { virtual_comp_group: invalid_attributes }, valid_session
        expect(assigns(:virtual_comp_group)).to be_a_new(VirtualCompGroup)
      end

      it "re-renders the 'new' template" do
        post :create, { virtual_comp_group: invalid_attributes }, valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        { name: 'Some another good competition group' }
      end

      it 'updates the requested virtual_comp_group' do
        virtual_comp_group = VirtualCompGroup.create! valid_attributes
        put :update, { id: virtual_comp_group.to_param, virtual_comp_group: new_attributes }, valid_session
        virtual_comp_group.reload
        expect(virtual_comp_group.name).to eq(new_attributes[:name])
      end

      it 'assigns the requested virtual_comp_group as @virtual_comp_group' do
        virtual_comp_group = VirtualCompGroup.create! valid_attributes
        put :update, { id: virtual_comp_group.to_param, virtual_comp_group: valid_attributes }, valid_session
        expect(assigns(:virtual_comp_group)).to eq(virtual_comp_group)
      end

      it 'redirects to the virtual_comp_group' do
        virtual_comp_group = VirtualCompGroup.create! valid_attributes
        put :update, { id: virtual_comp_group.to_param, virtual_comp_group: valid_attributes }, valid_session
        expect(response).to redirect_to(virtual_comp_group)
      end
    end

    context 'with invalid params' do
      it 'assigns the virtual_comp_group as @virtual_comp_group' do
        virtual_comp_group = VirtualCompGroup.create! valid_attributes
        put :update, { id: virtual_comp_group.to_param, virtual_comp_group: invalid_attributes }, valid_session
        expect(assigns(:virtual_comp_group)).to eq(virtual_comp_group)
      end

      it "re-renders the 'edit' template" do
        virtual_comp_group = VirtualCompGroup.create! valid_attributes
        put :update, { id: virtual_comp_group.to_param, virtual_comp_group: invalid_attributes }, valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested virtual_comp_group' do
      virtual_comp_group = VirtualCompGroup.create! valid_attributes
      expect do
        delete :destroy, { id: virtual_comp_group.to_param }, valid_session
      end.to change(VirtualCompGroup, :count).by(-1)
    end

    it 'redirects to the virtual_comp_groups list' do
      virtual_comp_group = VirtualCompGroup.create! valid_attributes
      delete :destroy, { id: virtual_comp_group.to_param }, valid_session
      expect(response).to redirect_to(virtual_comp_groups_url)
    end
  end
end
