module SponsorableLoading
  type sponsorable = Event | Tournament | VirtualCompetition

  extend ActiveSupport::Concern

  @sponsorable: sponsorable

  def load_sponsorable: () -> void

  def sponsorable_class: () -> (singleton(::Event) | singleton(::Tournament) | singleton(::VirtualCompetition) | nil)

  def authorize_sponsorable: () -> void
end
