class Api::V1::SpeedSkydivingCompetitions::CompetitorsController < Api::ApplicationController
  def index: () -> untyped

  def create: () -> untyped

  def update: () -> untyped

  def destroy: () -> untyped

  private

  def set_event: () -> untyped

  def competitor_params: () -> untyped
end
