module Events
  module Scoreboards
    class HungaryBoogie
      class CompetitorsCollection
        include Enumerable

        def initialize: (untyped competitors, untyped scoreboard) -> void

        def each: () ?{ () -> untyped } -> untyped

        def to_a: () -> untyped

        private

        attr_reader section_competitors: untyped

        attr_reader scoreboard: untyped

        def competitors: () -> untyped

        def map_competitors: (untyped collection) -> untyped

        def sort_competitors: (untyped collection) -> untyped
      end
    end
  end
end
